// Generated by IB v0.2.7 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation ParserError

@end


@implementation NSNotificationCenter

@end


@implementation NSURLRequest

@end


@implementation Camera

@end


@implementation UIView

@end


@implementation UIAlertView

@end


@implementation ClickedButton

@end


@implementation UIViewController

@end


@implementation PeriodicTimer

@end


@implementation Queue

@end


@implementation Timer

@end


@implementation UIView

@end


@implementation CameraViewController

@end


@implementation WelcomeViewController

@end



